# Generated by Django 5.2.4 on 2025-07-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet7', '0003_rename_student_csd'),
    ]

    operations = [
        migrations.AddField(
            model_name='csd',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
